# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build calculator app"
  lane :build_calculator do
    scan(
      project: "TurboCalculator.xcodeproj",
      scheme: "TurboCalculator",
      clean: true,
      build_for_testing: true,
      derived_data_path: "DerivedData"
    )
  end

  desc "Run tests of calculator app"
  lane :test_app do
    scan(
      project: "TurboCalculator.xcodeproj",
      scheme: "TurboCalculator",
      derived_data_path: "DerivedData",
      output_directory: "Report",
      device: "iPhone 15",
      app_identifier: "QAGuru.Calculator",
      reinstall_app: true,
      test_without_building: true,
      result_bundle: true
    )
  end
end
